### ISSUE TITLE
Fails installing in CentOS

### ISSUE THREAD

**Issue by xoseperez** [y-a-v-a/node-gd#24]
I'm receiving this error all the time.

```
> node-gd@1.3.0 install /home/user/workspace/dashboard/node_modules/node-gd
> node-gyp rebuild

make: Entering directory `/home/user/workspace/dashboard/node_modules/node-gd/build'
  CXX(target) Release/obj.target/node_gd/cpp/addon.o
make: g++: Command not found
make: *** [Release/obj.target/node_gd/cpp/addon.o] Error 127
make: Leaving directory `/home/user/workspace/dashboard/node_modules/node-gd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-042stab111.12
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/workspace/dashboard/node_modules/node-gd
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.10.0-042stab111.12
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-gd"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-gd@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gd@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-gd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-gd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-gd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/workspace/dashboard/npm-debug.log

```

**Comment by y-a-v-a** [comment]
Aren't you missing CentOS compile tools? As it says it cannot find g++: `make: g++: Command not found`, you probably need to install build tools. I don't have a CentOS at my disposal so I'd suggest to google for it.

**Comment by y-a-v-a** [comment]
@xoseperez if you have any notable follow up on this, please feel free to comment and reopen.

**Comment by xoseperez** [comment]
I hadn't had time until now. Sorry. But that solved the issue. I should have read it closely.

**Comment by y-a-v-a** [comment]
Thanks for the response, I'll try to make it more explicit in the documentation.
