### ISSUE TITLE
gd.openFile is not a function

### ISSUE THREAD

**Issue by gmemstr** [y-a-v-a/node-gd#27]
This only seems to occur in the 6.2.2 Node.js Docker container. Full source code and stuff is [here](https://github.com/GGServers/MinecraftBanner/tree/v1), works fine under 6.2.2 on my local Arch install.

```
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
npm info lifecycle minecraftbanner@1.0.0~prestart: minecraftbanner@1.0.0
npm info lifecycle minecraftbanner@1.0.0~start: minecraftbanner@1.0.0

> minecraftbanner@1.0.0 start /usr/src/banner
> node index.js

/usr/src/banner/lib/generator.js:18
    gd.openFile('template/image/' + template + ".png", function(err, img) {
       ^

TypeError: gd.openFile is not a function
    at image (/usr/src/banner/lib/generator.js:18:8)
    at /usr/src/banner/lib/generator.js:47:17
    at Object.callback (/usr/src/banner/lib/generator.js:13:13)
    at Class.module.exports.Class.extend.done (/usr/src/banner/node_modules/gamedig/protocols/core.js:75:42)
    at Class.module.exports.Class.extend.fatal (/usr/src/banner/node_modules/gamedig/protocols/core.js:35:8)
    at Socket.<anonymous> (/usr/src/banner/node_modules/gamedig/protocols/core.js:242:21)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12)

npm info lifecycle minecraftbanner@1.0.0~start: Failed to exec start script
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! minecraftbanner@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minecraftbanner@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minecraftbanner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minecraftbanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minecraftbanner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/banner/npm-debug.log
```

**Comment by y-a-v-a** [comment]
It might be that the Docker environment has a lower version of libgd. You can find that out by calling `gd.getGDVersion()`.

**Comment by y-a-v-a** [comment]
In order to use the `gd.openFile`, you will need at least libgd version 2.1.1. The other option is to use `gd.openPng` because as your example code shows, you already know it's a .png file.

**Comment by gmemstr** [comment]
Decided to switch to `gd.openPng`, was using the latest `libgd-dev` package for Debian. Thanks anyways.

**Comment by y-a-v-a** [comment]
Ok great that it works for you. But I think that it might exactly be the issue. Debian is always a bit behind when it comes to lib versions.
