### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by NachtRitter** [y-a-v-a/node-gd#42]
Which environment-specific build tools shoud be installed on Alpine Linux?
I tried install make gcc python g++ gd-dev, but I get error during node-gyp build
```
node-gd@1.2.0 install /var/www/node_modules/node-gd
 node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.7.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/node_modules/node-gd/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.7.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.7.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/node_modules/node-gd',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gdlib-config: warning: this script is deprecated; please use the pkg-config file instead.
gyp: Call to './util.sh GD_PNG' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-64-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/node_modules/node-gd
gyp ERR! node -v v4.7.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm info node-gd@1.2.0 Failed to exec install script
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
```

**Comment by y-a-v-a** [comment]
Hi thanks for reaching out.
I see you use node-gd@1.2.0. I'd suggest to first try to use node-gd@1.4.0 which is the latest version. If build problems still occur, please let me know!
Cheers,
Vincent

**Comment by NachtRitter** [comment]
@y-a-v-a , thanks for your advice. I missed that my shrinkwrapped version was 1.2.0.
All finished fine for v1.4.0. So you may add to README that for Alpine Linux packages make gcc python g++ gd-dev are required:
`apk add --no-cache make gcc python g++ gd-dev`

**Comment by y-a-v-a** [comment]
I'll see what I can do. Thanks for the update!
