### ISSUE TITLE
npm install fails on nodejs version 12.5

### ISSUE THREAD

**Issue by buraktamturk** [y-a-v-a/node-gd#70]
Hello,

I am having this exception while installing node-gd. The operating system is MacOS Mojave. NodeJS version is 12.5.0 and I have installed pkg-config and gd via homebrew.

Is there anything that I miss? or is the library incompatible with the NodeJS 12?

```
> node-gyp rebuild

  CXX(target) Release/obj.target/node_gd/cpp/addon.o
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use
      Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(v8::Isolate::GetCurrent()->GetCurrentContext())          \
           ^
<scratch space>:204:1: note: expanded from here
ToBoolean
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2523:3: note: 'ToBoolean' has been explicitly marked
      deprecated here
  V8_DEPRECATED("ToBoolean can never throw. Use Local version.",
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw.
      Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:211:1: note: expanded from here
BooleanValue
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2561:3: note: 'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to
      'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:183:7: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'v8::Isolate *' to
      'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:183:7: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from 'v8::Isolate *' to
      'v8::Local<v8::Context> &&' for 1st argument
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:187:13: note: candidate template ignored: could not
      match 'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:4126:22: note: passing argument to parameter 'context'
      here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:5381:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:173:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:166:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:159:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:916:44: error: no matching member function for call to 'ToString'
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~^~~~~~~~
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2528:44: note: candidate function not viable: requires
      single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2544:31: note: candidate function not viable: requires
      single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:926:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type
      'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2738:26: note: passing argument to parameter 'isolate'
      here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:173:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1538:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1544:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1550:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3367:3: note: 'Set' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1556:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1562:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
../../nan/nan.h:1567:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked
      deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:2365:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note:
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:2365:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Weak objects are always
      considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when
      trying to keep an object alive. [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly
      marked deprecated here
  V8_DEPRECATED(
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../cpp/addon.cc:1:
In file included from ../../nan/nan.h:2365:
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note:
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../cpp/addon.cc:3:
In file included from ../cpp/node_gd.cc:27:
../cpp/createworker.cc:40:78: error: too few arguments to function call, single argument 'context' was not
      specified
      v8::MaybeLocal<v8::Object> _image = Nan::NewInstance(func->GetFunction(), _argc, _argv);
                                                           ~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:291:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(0, width);
  ^~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:292:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(1, height);
  ^~~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:307:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(0, width);
  ^~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:308:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(1, height);
  ^~~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:315:3: error: too few arguments to function call, single argument 'context' was not
      specified
  RETURN_IMAGE(im);
  ^~~~~~~~~~~~~~~~
../cpp/node_gd.cc:144:70: note: expanded from macro 'RETURN_IMAGE'
    MaybeLocal<Object> instance = Nan::NewInstance(func->GetFunction(), argc, argv);\
                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:320:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(0, width);
  ^~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:321:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(1, height);
  ^~~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:336:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(0, width);
  ^~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:337:3: error: too few arguments to function call, single argument 'context' was not
      specified
  REQ_INT_ARG(1, height);
  ^~~~~~~~~~~~~~~~~~~~~~
../cpp/node_gd.cc:84:29: note: expanded from macro 'REQ_INT_ARG'
  VAR = info[I]->Int32Value();
        ~~~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../cpp/addon.cc:3:
../cpp/node_gd.cc:344:3: error: too few arguments to function call, single argument 'context' was not
      specified
  RETURN_IMAGE(im);
  ^~~~~~~~~~~~~~~~
../cpp/node_gd.cc:144:70: note: expanded from macro 'RETURN_IMAGE'
    MaybeLocal<Object> instance = Nan::NewInstance(func->GetFunction(), argc, argv);\
                                                   ~~~~~~~~~~~~~~~~~ ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/buraktamturk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
13 warnings and 20 errors generated.
make: *** [Release/obj.target/node_gd/cpp/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gd@1.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-gd@1.5.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/buraktamturk/.npm/_logs/2019-07-04T18_26_29_996Z-debug.log
```

**Comment by y-a-v-a** [comment]
Thanks for notifying, I haven't tested node-gd against node.js 12 yet. Will do so somewhere the upcoming weeks and might release a new version of node-gd.
Regards,
Vincent
